name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username $DOCKER_HUB_USERNAME --password-stdin

      - name: Build, tag, and push the Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY_NAME }}
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:$IMAGE_TAG .
          docker tag $DOCKER_HUB_REPOSITORY:$IMAGE_TAG $DOCKER_HUB_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_HUB_REPOSITORY:$IMAGE_TAG

      - name: Deploy to ECS
        env:
          CLUSTER_NAME: fusion-api-cluster
          SERVICE_NAME: fusion_api
          TASK_DEFINITION_FILE: ecs-task-def.json
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
